version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_password  # ルートパスワードを設定
      DB_DATABASE: task_management
      DB_USERNAME: kawasaki
      DB_PASSWORD: your_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:1.19.6
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql-db:
